name: "Bug Report 错误报告"
description: "Create a bug report 创建一个错误报告"
title: "[BUG] Some problem..."
labels: ["bug"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug 描述你遇到的错误
      description: |
        A clear and concise description of what the bug is. 一段简短的对于你遇到的错误的描述.
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior 期待的行为
      description: |
        A clear and concise description of what you expected to happen. 一段简短的对于你期待的行为的描述.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots 屏幕截图
      description: |
       If applicable, add screenshots to help explain your problem. 如果可以的话, 提供屏幕截图对解决问题很有帮助.
  - type: textarea
    id: environment
    attributes:
      label: Build Environment 构建环境
      description: |
        Please try to use Hugo **extended** version before opening the issue. 请在创建 issue 之前尝试使用 Hugo **extended** 版本.
      placeholder: |
        - OS: [e.g. Windows 10, macOS, Ubuntu]
        - Theme version/commit [e.g. 0.2.0, 2ccba79]
        - Hugo version [e.g. 0.69.0]        
  - type: textarea
    id: preview
    attributes:
      label: Preview Environment 预览环境
      placeholder: |
        - OS: [e.g. Windows 10, macOS, Ubuntu, iOS, Android]
        - Browser [e.g. Chrome, Safari, Firefox]
  - type: textarea
    id: additional
    attributes:
      label: Additional Information 补充信息
      description: |
        Configuration files or front matter code... 配置文件或者前置参数的代码...
