name: "Feature request 功能请求"
description: "Suggest an idea for this project 为这个项目提供一个建议"
title: "[FEATURE] Some feature"
labels: ["new feature"]
body:
    - type: textarea
      id: describe
      attributes:
        label: Describe the feature you want 描述你的功能需求
        description: |
            Please submit new issues for different features.
            请针对不同的功能建议提交新的 issue.    
        placeholder: |
          I recommend adding this feature.
          我希望添加这样的一个功能...    
    - type: textarea
      id: reference
      attributes:
        label: Useful reference 有价值的参考
        description: |
          If available, provide useful links to fulfill the feature. 如果可以的话, 提供实现这个功能的相关参考链接.
